2018-08-29 15:46:03,476 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-29 15:47:27,805 ERROR: Exception on /edit_profile [POST] [in /home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/reijer/projects/microblog/app/routes.py", line 85, in edit_profile
    db.session.commit()
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 768, in _emit_update_statements
    execute(statement, multiparams)
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/reijer/.virtualenvs/microblog/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username [SQL: u'UPDATE user SET username=?, about_me=? WHERE user.id = ?'] [parameters: (u'reijer', u'Two roads diverged in a yellow wood,\r\nAnd sorry I could not travel both\r\nAnd be one traveler, long I stood\r\n', 4)] (Background on this error at: http://sqlalche.me/e/gkpj)
2018-08-29 16:02:29,028 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 10:22:17,385 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 10:46:10,279 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 10:46:20,043 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 10:46:39,690 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 10:46:44,216 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 13:42:46,929 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 13:47:21,559 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 13:49:47,690 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 13:52:03,669 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 13:59:36,794 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 14:01:08,957 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 14:04:48,480 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 14:05:57,096 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 14:06:30,929 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 14:06:55,547 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 14:07:41,290 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 14:24:24,081 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 14:26:18,295 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 15:06:15,151 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
2018-08-31 15:08:30,933 INFO: Microblog startup [in /home/reijer/projects/microblog/app/__init__.py:43]
